# TODO: change ports to expose once we have a reverse proxy in place

version: '2'
services:
  # TODO: have a pretty web portal that reverse proxies to all the others
  # TODO: openvpn client
  # TODO: flexget

  # music manager
  beets:
    image: linuxserver/beets
    ports:
     - "8337:8337/tcp"
    volumes:
      # headphones is setup to put music into the beets dir
      - ./data/downloads/beets:/downloads
      - ./data/media/music:/music
      - ./data/var/beets:/config

  # audiobook player
  # TODO: I might just use Plex for this
  booksonic:
    image: ironicbadger/booksonic
    ports:
      - "8081:8080/tcp"
    volumes:
      - ./data/media/audiobook:/var/audiobooks
      - ./data/media/podcasts:/var/Podcasts
      - ./data/var/booksonic:/var/booksonic

  # torrent downloader
  # default user/password of admin/deluge at http://localhost:8112/
  deluge:
    image: linuxserver/deluge
    environment:
      - TZ=US/Eastern
    ports:
      - "8112:8112/tcp"
      - "58846:58846/tcp"
      - "58946:58946/tcp"
      - "58946:58946/udp"
    volumes:
      - ./data/downloads/deluge:/downloads
      # TODO: make use of the downloading dir
      - ./data/downloading/deluge:/incoming
      - ./data/var/deluge:/config

  # automated music search
  headphones:
    image: linuxserver/headphones
    environment:
      - TZ=US/Eastern
    ports:
      - "8181:8181/tcp"
    volumes:
      # beets will move the music into ./data/media/music
      - "./data/downloads/beets:/music"
      - "./data/downloads/music:/downloads"
      - "./data/var/headphones:/config"

  # usenet search
  hydra:
    image: linuxserver/hydra
    environment:
      - TZ=US/Eastern
    ports:
      - "5075:5075/tcp"
    volumes:
      - ./data/downloads/hydra:/downloads
      - ./data/var/hydra:/config

  # torrent search proxy
  jackett:
    image: linuxserver/jackett
    environment:
      - TZ=US/Eastern
    ports:
      - "9117:9177/tcp"
    volumes:
      - ./data/blackhole:/downloads
      - ./data/var/jackett:/config

  # automated book search
  lazylibrarian:
    image: linuxserver/lazylibrarian
    ports:
      - "5299:5299/tcp"
    volumes:
      - ./data/downloads/books:/downloads
      - ./data/media/books:/books
      - ./data/var/lazylibrarian:/config

  # automated comic book search
  mylar:
    image: linuxserver/mylar
    environment:
      - TZ=US/Eastern
    ports:
      - "8090:8090/tcp"
    volumes:
      - ./data/downloads/mylar:/downloads
      - ./data/media/comics:/comics
      - ./data/var/mylar:/config

  # media player
  # Webui can be found at http://localhost:32400/web
  plex:
    image: linuxserver/plex
    environment:
      - TZ=US/Eastern
      - VERSION=latest
    # network_mode: host
    # port forwards work fine for everything but 5353/1900
    ports:
      - "32400:32400/tcp"
      - "32400:32400/udp"
      - "32469:32469/tcp"
      - "32469:32469/udp"
    volumes:
      - ./data/media/audiobook:/data/audiobook
      - ./data/media/movies:/data/movies
      - ./data/media/music:/data/music
      - ./data/media/tv:/data/tv
      - ./data/var/plex:/config
      - ./data/var/plex_transcode:/transcode

  plexpy:
    image: linuxserver/plexpy
    depends_on:
      - plex
    environment:
      - TZ=US/Eastern
    ports:
      - "8182:8181/tcp"
    volumes:
      - ./data/var/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
      - ./data/var/plexpy:/config

  # newsgroup downloader
  # TODO: automate setup of categories
  sabnzbd:
    image: linuxserver/sabnzbd
    environment:
      - TZ=US/Eastern
    ports:
      - "8082:8080/tcp"
      - "9090:9090/tcp"
    volumes:
      - ./data/downloading/sabnzbd:/incomplete-downloads
      - ./data/downloads:/downloads
      - ./data/var/sabnzbd:/config

  # automated tv search
  sonarr:
    image: linuxserver/sonarr
    depends_on:
      - sabnzbd
    environment:
      - TZ=US/Eastern
    ports:
      - "8989:8989/tcp"
    volumes:
      - ./data/downloads/tv:/downloads
      - ./data/media/tv:/tv
      - ./data/var/sonarr:/config
      # - /dev/rtc:/dev/rtc:ro

  tor:
    image: bwstitt/tor
    expose:
      - "9050"
    volumes:
      - ./config/torrc:/etc/tor/torrc:ro
      # TODO: does this cover up the /var/lib/tor/.arm/armrc that comes with the container?
      - ./data/var/tor:/var/lib/tor
      # - /dev/rtc:/dev/rtc:ro

  web:
    image: bwstitt/media-suite-web
    ports:
      - "8888:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
