# TODO: change ports to expose once we have a reverse proxy in place

version: '2'
services:
  # TODO: have a pretty web portal that reverse proxies to all the others
  # TODO: openvpn client
  # TODO: flexget

  # music manager
  beets:
    image: linuxserver/beets
    ports:
     - "8337:8337/tcp"
    volumes:
      - ./data/beets:/config
      # headphones is setup to put music into the beets dir
      - ./downloads/beets:/downloads
      - ./media/music:/music

  # audiobook player
  # TODO: I might just use Plex for this
  booksonic:
    image: ironicbadger/booksonic
    ports:
      - "8081:8080/tcp"
    volumes:
      - ./data/booksonic:/var/booksonic
      - ./media/audiobook:/var/audiobooks
      - ./media/podcasts:/var/Podcasts

  # torrent downloader
  # default user/password of admin/deluge at http://localhost:8112/
  deluge:
    image: linuxserver/deluge
    environment:
      - TZ=US/Eastern
    ports:
      - "8112:8112/tcp"
      - "58846:58846/tcp"
      - "58946:58946/tcp"
      - "58946:58946/udp"
    volumes:
      - ./data/deluge:/config
      - ./downloads/deluge:/downloads
      # TODO: make use of this
      - ./downloading/deluge:/incoming

  # automated music search
  headphones:
    image: linuxserver/headphones
    environment:
      - TZ=US/Eastern
    ports:
      - "8181:8181/tcp"
    volumes:
      - "./data/headphones:/config"
      # beets will move the music into ./media/music
      - "./downloads/beets:/music"
      - "./downloads/music:/downloads"

  # usenet search
  hydra:
    image: linuxserver/hydra
    environment:
      - TZ=US/Eastern
    ports:
      - "5075:5075/tcp"
    volumes:
      - ./data/hydra:/config
      - ./downloads/hydra:/downloads

  # torrent search proxy
  jackett:
    image: linuxserver/jackett
    environment:
      - TZ=US/Eastern
    ports:
      - "9117:9177/tcp"
    volumes:
      - ./data/blackhole:/downloads
      - ./data/jackett:/config

  # automated book search
  lazylibrarian:
    image: linuxserver/lazylibrarian
    ports:
      - "5299:5299/tcp"
    volumes:
      - ./data/lazylibrarian:/config
      - ./downloads/books:/downloads
      - ./media/books:/books

  # automated comic book search
  mylar:
    image: linuxserver/mylar
    environment:
      - TZ=US/Eastern
    ports:
      - "8090:8090/tcp"
    volumes:
      - ./data/mylar:/config
      - ./downloads/mylar:/downloads
      - ./media/comics:/comics

  # media player
  # Webui can be found at http://localhost:32400/web
  plex:
    image: linuxserver/plex
    environment:
      - TZ=US/Eastern
      - VERSION=latest
    # network_mode: host
    # port forwards work fine for everything but 5353/1900
    ports:
      - "32400:32400/tcp"
      - "32400:32400/udp"
      - "32469:32469/tcp"
      - "32469:32469/udp"
    volumes:
      - ./data/plex:/config
      - ./data/plex_transcode:/transcode
      - ./media/audiobook:/data/audiobook
      - ./media/movies:/data/movies
      - ./media/music:/data/music
      - ./media/tv:/data/tv

  plexpy:
    image: linuxserver/plexpy
    depends_on:
      - plex
    environment:
      - TZ=US/Eastern
    ports:
      - "8182:8181/tcp"
    volumes:
      - ./data/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
      - ./data/plexpy:/config

  # newsgroup downloader
  # TODO: automate setup of categories
  sabnzbd:
    image: linuxserver/sabnzbd
    environment:
      - TZ=US/Eastern
    ports:
      - "8082:8080/tcp"
      - "9090:9090/tcp"
    volumes:
      - ./data/sabnzbd:/config
      - ./downloading/sabnzbd:/incomplete-downloads
      - ./downloads:/downloads

  # automated tv search
  sonarr:
    image: linuxserver/sonarr
    depends_on:
      - sabnzbd
    environment:
      - TZ=US/Eastern
    ports:
      - "8989:8989/tcp"
    volumes:
      - ./data/sonarr:/config
      - ./downloads/tv:/downloads
      - ./media/tv:/tv
      # - /dev/rtc:/dev/rtc:ro

  tor:
    image: bwstitt/tor
    expose:
      - "9050"
    volumes:
      - ./config/torrc:/etc/tor/torrc:ro
      - ./data/tor:/var/lib/tor
      # - /dev/rtc:/dev/rtc:ro
